### ISSUE TITLE
文档完善

### ISSUE THREAD

**Issue by Zjieke** [easycode8/easy-log#1]
你好，可以增加以下几个模块的说明
[easy-log-core]
[easy-log-data-mybatis-plus]
[easy-log-spring-boot-starter]
[easy-log-web]

[如何记录数据操作快照数据(数据修改对比,删除历史记录)](https://easycode8.github.io/easy-log/#/guide/advanced?id=%e5%a6%82%e4%bd%95%e8%ae%b0%e5%bd%95%e6%95%b0%e6%8d%ae%e6%93%8d%e4%bd%9c%e5%bf%ab%e7%85%a7%e6%95%b0%e6%8d%ae%e6%95%b0%e6%8d%ae%e4%bf%ae%e6%94%b9%e5%af%b9%e6%af%94%e5%88%a0%e9%99%a4%e5%8e%86%e5%8f%b2%e8%ae%b0%e5%bd%95)

文档这部分没有完善。

**Comment by easycode8** [comment]
好的，近期会补充下。好了, 再回复你

**Comment by easycode8** [comment]
> 你好，可以增加以下几个模块的说明 [easy-log-core] [easy-log-data-mybatis-plus] [easy-log-spring-boot-starter] [easy-log-web]
> 
> [如何记录数据操作快照数据(数据修改对比,删除历史记录)](https://easycode8.github.io/easy-log/#/guide/advanced?id=%e5%a6%82%e4%bd%95%e8%ae%b0%e5%bd%95%e6%95%b0%e6%8d%ae%e6%93%8d%e4%bd%9c%e5%bf%ab%e7%85%a7%e6%95%b0%e6%8d%ae%e6%95%b0%e6%8d%ae%e4%bf%ae%e6%94%b9%e5%af%b9%e6%af%94%e5%88%a0%e9%99%a4%e5%8e%86%e5%8f%b2%e8%ae%b0%e5%bd%95)
> 
> 文档这部分没有完善。

好的，近期会完善下. 好的再回复你

**Comment by easycode8** [comment]
已经完善了文档内容。

**Comment by easycode8** [comment]
已经完善了文档内容

**Comment by easycode8** [comment]
已经完善了文档内容

**Comment by easycode8** [comment]
发布了1.0.4版本, 也完善了文档内容
![image](https://github.com/easycode8/easy-log/assets/125171638/80da7056-b5a8-4c91-b12e-7cfec8f91e40)
![image](https://github.com/easycode8/easy-log/assets/125171638/1e855a94-aa77-41ad-80af-8a780ae7610f)

**Comment by easycode8** [comment]
你好, 已经发布了1.0.4版本优化了一些功能, isssues提到部分文档已经完善了
