### ISSUE TITLE
启动速度异常

### ISSUE THREAD

**Issue by Zjieke** [easycode8/easy-log#2]
你好，增加以后，项目启动速度达到半小时，
两个项目组的同事都遇到该问题，

不知能否测试下。

**Comment by easycode8** [comment]
你提供的信息太少了，当前easy-log是使用springboot 2.3.2.RELEASE jdk11开发的，也是验证过的。你的项目是使用的是什么配置，然后自动开启记录日志不是有很多项，你尝试关闭几个自动记录日志项目, 看下能否初步判断下哪个自动配置,导致缓慢

**Comment by easycode8** [comment]
1.0.11 增加判断启动性能检查。有项目启动耗时和单独测试了aop性能对比。因为设计上默认为了可以最大程度懒人记录日志，是不限制aop扫描的项目范围，几乎所有bean都检查。如果业务项目本来代码量就很庞大,是会增加启动消耗。

补充了可选择扫描范围配置：可以设置aop扫描类基础包:  https://gitee.com/easycode8/easy-log/issues/I7YDD2

spring:
  easy-log:
    scan-packages:
      - com.easycode8.easylog.sample #比如项目业务包根目录
