### ISSUE TITLE
是否支持获取FORM表单参数

### ISSUE THREAD

**Issue by CloverHQ** [easycode8/easy-log#4]
1.是否支持获取FORM表单参数
2.涉及文件上传相关是否可以记录或忽略File文件参数
3.是否支持仅修改单个请求参数，其余请求参数照常输出？

**Comment by CloverHQ** [comment]
4.Java8项目引入启动报错

**Comment by easycode8** [comment]
1和2 可以获取表单参数: 文件上传就是表单参数。上传文件会自动忽略文件对象(文件对象没有可读性)
表单上传 + 文件上传示例：
![image](https://github.com/easycode8/easy-log/assets/125171638/d075287c-2983-4b25-a560-b40f12c15c61)
记录效果:
![image](https://github.com/easycode8/easy-log/assets/125171638/c7a01c8c-7267-49bd-9e73-b77ca0a28af5)

3. 第三点没看明白什么意思
4. 正常jdk版本不影响框架使用，如果是框架报错。提供日志信息

**Comment by CloverHQ** [comment]
> 1和2 可以获取表单参数: 文件上传就是表单参数。上传文件会自动忽略文件对象(文件对象没有可读性) 表单上传 + 文件上传示例： ![image](https://user-images.githubusercontent.com/125171638/285353440-d075287c-2983-4b25-a560-b40f12c15c61.png) 记录效果: ![image](https://user-images.githubusercontent.com/125171638/285353566-c7a01c8c-7267-49bd-9e73-b77ca0a28af5.png)
> 
> 3. 第三点没看明白什么意思
> 4. 正常jdk版本不影响框架使用，如果是框架报错。提供日志信息
<img width="1522" alt="image" src="https://github.com/easycode8/easy-log/assets/26052169/6db8db67-235c-498f-9a7e-2d9a132b70be">

**Comment by CloverHQ** [comment]
> > 1和2 可以获取表单参数: 文件上传就是表单参数。上传文件会自动忽略文件对象(文件对象没有可读性) 表单上传 + 文件上传示例： ![image](https://user-images.githubusercontent.com/125171638/285353440-d075287c-2983-4b25-a560-b40f12c15c61.png) 记录效果: ![image](https://user-images.githubusercontent.com/125171638/285353566-c7a01c8c-7267-49bd-9e73-b77ca0a28af5.png)
> > 
> > 3. 第三点没看明白什么意思
> > 4. 正常jdk版本不影响框架使用，如果是框架报错。提供日志信息
> 
> <img alt="image" width="1522" src="https://user-images.githubusercontent.com/26052169/285380225-6db8db67-235c-498f-9a7e-2d9a132b70be.png">

使用了@EasyLog出现异常

**Comment by easycode8** [comment]
确实有bug, 当前我是使用了java11开发编译的. 这个方法java8没有。作为以下修改，然后使用java8编译。
Map.entry(p.key(), p.value()) -> new AbstractMap.SimpleEntry<>(p.key(), p.value())

1.0.12 版本解决。今天回发布，晚点升级下依赖再试下

**Comment by easycode8** [comment]
> > > 1和2 可以获取表单参数: 文件上传就是表单参数。上传文件会自动忽略文件对象(文件对象没有可读性) 表单上传 + 文件上传示例： ![image](https://user-images.githubusercontent.com/125171638/285353440-d075287c-2983-4b25-a560-b40f12c15c61.png) 记录效果: ![image](https://user-images.githubusercontent.com/125171638/285353566-c7a01c8c-7267-49bd-9e73-b77ca0a28af5.png)
> > > 
> > > 3. 第三点没看明白什么意思
> > > 4. 正常jdk版本不影响框架使用，如果是框架报错。提供日志信息
> > 
> > 
> > <img alt="image" width="1522" src="https://user-images.githubusercontent.com/26052169/285380225-6db8db67-235c-498f-9a7e-2d9a132b70be.png">
> 
> 使用了@easylog出现异常

确实有bug, 当前我是使用了java11开发编译的. 这个方法java8没有。作为以下修改，然后使用java8编译。
Map.entry(p.key(), p.value()) -> new AbstractMap.SimpleEntry<>(p.key(), p.value())

1.0.12 版本解决。今天回发布，晚点升级下依赖再试下

**Comment by CloverHQ** [comment]
> > > > 1和2 可以获取表单参数: 文件上传就是表单参数。上传文件会自动忽略文件对象(文件对象没有可读性) 表单上传 + 文件上传示例： ![image](https://user-images.githubusercontent.com/125171638/285353440-d075287c-2983-4b25-a560-b40f12c15c61.png) 记录效果: ![image](https://user-images.githubusercontent.com/125171638/285353566-c7a01c8c-7267-49bd-9e73-b77ca0a28af5.png)
> > > > 
> > > > 3. 第三点没看明白什么意思
> > > > 4. 正常jdk版本不影响框架使用，如果是框架报错。提供日志信息
> > > 
> > > 
> > > <img alt="image" width="1522" src="https://user-images.githubusercontent.com/26052169/285380225-6db8db67-235c-498f-9a7e-2d9a132b70be.png">
> > 
> > 
> > 使用了@easylog出现异常
> 
> 确实有bug, 当前我是使用了java11开发编译的. 这个方法java8没有。作为以下修改，然后使用java8编译。 Map.entry(p.key(), p.value()) -> new AbstractMap.SimpleEntry<>(p.key(), p.value())
> 
> 1.0.12 版本解决。今天回发布，晚点升级下依赖再试下

OK

**Comment by CloverHQ** [comment]
> > > > 1和2 可以获取表单参数: 文件上传就是表单参数。上传文件会自动忽略文件对象(文件对象没有可读性) 表单上传 + 文件上传示例： ![image](https://user-images.githubusercontent.com/125171638/285353440-d075287c-2983-4b25-a560-b40f12c15c61.png) 记录效果: ![image](https://user-images.githubusercontent.com/125171638/285353566-c7a01c8c-7267-49bd-9e73-b77ca0a28af5.png)
> > > > 
> > > > 3. 第三点没看明白什么意思
> > > > 4. 正常jdk版本不影响框架使用，如果是框架报错。提供日志信息
> > > 
> > > 
> > > <img alt="image" width="1522" src="https://user-images.githubusercontent.com/26052169/285380225-6db8db67-235c-498f-9a7e-2d9a132b70be.png">
> > 
> > 
> > 使用了@easylog出现异常
> 
> 确实有bug, 当前我是使用了java11开发编译的. 这个方法java8没有。作为以下修改，然后使用java8编译。 Map.entry(p.key(), p.value()) -> new AbstractMap.SimpleEntry<>(p.key(), p.value())
> 
> 1.0.12 版本解决。今天回发布，晚点升级下依赖再试下

今天会更新吗

**Comment by easycode8** [comment]
> > > > > 1和2 可以获取表单参数: 文件上传就是表单参数。上传文件会自动忽略文件对象(文件对象没有可读性) 表单上传 + 文件上传示例： ![image](https://user-images.githubusercontent.com/125171638/285353440-d075287c-2983-4b25-a560-b40f12c15c61.png) 记录效果: ![image](https://user-images.githubusercontent.com/125171638/285353566-c7a01c8c-7267-49bd-9e73-b77ca0a28af5.png)
> > > > > 
> > > > > 3. 第三点没看明白什么意思
> > > > > 4. 正常jdk版本不影响框架使用，如果是框架报错。提供日志信息
> > > > 
> > > > 
> > > > <img alt="image" width="1522" src="https://user-images.githubusercontent.com/26052169/285380225-6db8db67-235c-498f-9a7e-2d9a132b70be.png">
> > > 
> > > 
> > > 使用了@easylog出现异常
> > 
> > 
> > 确实有bug, 当前我是使用了java11开发编译的. 这个方法java8没有。作为以下修改，然后使用java8编译。 Map.entry(p.key(), p.value()) -> new AbstractMap.SimpleEntry<>(p.key(), p.value())
> > 1.0.12 版本解决。今天回发布，晚点升级下依赖再试下
> 
> 今天会更新吗

上周五就更新了。 可以使用1.0.12

**Comment by CloverHQ** [comment]
> > > > > > 1和2 可以获取表单参数: 文件上传就是表单参数。上传文件会自动忽略文件对象(文件对象没有可读性) 表单上传 + 文件上传示例： ![image](https://user-images.githubusercontent.com/125171638/285353440-d075287c-2983-4b25-a560-b40f12c15c61.png) 记录效果: ![image](https://user-images.githubusercontent.com/125171638/285353566-c7a01c8c-7267-49bd-9e73-b77ca0a28af5.png)
> > > > > > 
> > > > > > 3. 第三点没看明白什么意思
> > > > > > 4. 正常jdk版本不影响框架使用，如果是框架报错。提供日志信息
> > > > > 
> > > > > 
> > > > > <img alt="image" width="1522" src="https://user-images.githubusercontent.com/26052169/285380225-6db8db67-235c-498f-9a7e-2d9a132b70be.png">
> > > > 
> > > > 
> > > > 使用了@easylog出现异常
> > > 
> > > 
> > > 确实有bug, 当前我是使用了java11开发编译的. 这个方法java8没有。作为以下修改，然后使用java8编译。 Map.entry(p.key(), p.value()) -> new AbstractMap.SimpleEntry<>(p.key(), p.value())
> > > 1.0.12 版本解决。今天回发布，晚点升级下依赖再试下
> > 
> > 
> > 今天会更新吗
> 
> 上周五就更新了。 可以使用1.0.12

试了下可以了 谢谢
